lang = {
    "english": {
        "contakuto":    "Contakuto",
        "search":       "Search",
        "edit":         "Edit",
        "remove":       "Remove",
        "signout":      "Sign out",
        "cancel":       "Cancel",
        "ok":           "OK",
        "crop":         "Crop",
        "profile_picture":  "Profile picture",
        "profile_picture_setting":         "Add or change profile picture.",
        "profile_picture_description":      "Profile picture is a small identifying picture of the account's owner.",
        "username": "Username",
        "fullname": "Full Name",
        "fullname_setting":         "Change your fullname.",
        "fullname_description":     "<p>- Full name is a text which is shown on top right corner of the app.</p>\n<p>- Full name is only allowed to contain maximum 22 characters.</p>",
        "password": "Password",
        "password_setting":         "Change your password.",
        "password_description":     "<p>- Password must contain minimum 6 characters and maximum 14 characters.</p><p>- Password is only allowed to contain alphabet and numberic characters.</p>",
        "current_password":         "Current password",
        "new_password":             "New passowrd",
        "confirm_password":         "Confirm password",
        "wrong_current_password":   "Wrong current password",
        "wrong_current_password_description":   "Your current password is wrong. Please enter again!",
        "wrong_confirm_password":   "Wrong confirmation password",
        "wrong_confirm_password_description":   "Your confirmation password is wrong. Please enter again.",
        "pin_description":          "<p>- PIN is a private code used when recovering password.</p><p>- PIN contains 4 numbers.",
        "pin_setting":              "Change your password",
        "pin":                      "PIN",
        "current_pin":              "Current PIN",
        "new_pin":                  "New PIN",
        "confirm_pin":              "Confirm PIN",
        "wrong_current_pin":        "Wrong current PIN",
        "wrong_current_pin_description":    "Your current PIN is wrong. Please enter again!",
        "wrong_confirm_pin":        "Wrong confirmation PIN",
        "wrong_confirm_pin_description":    "Your confirmation PIN is wrong. Please enter again.",
        "language_description":     "<p>- This setting sets up which language is displayed in the application.</p><p>- Currently, only English, Vietnamese and Japanese are supported..</p>",
        "language_setting":         "Change your language.",
        "choose_language":          "Choose a language:",
        "language":                 "Language",
        "language_english":         "English",
        "language_vietnamese":      "Vietnamese",
        "language_japanese":        "Japanese",
        "theme_description":        "<p>- This setting sets the appearance of the app.</p><p>- Currently there are only 2 options which are light and dark themes.</p>",
        "theme_setting":            "Change app's appearance",
        "theme":                    "Theme",
        "theme_light":              "Light",
        "theme_dark":               "Dark",
        "reboot_require":           "Reboot required",
        "reboot_require_description":   "This setting requires rebooting to take effect!\nWould you like to reboot?",
        "save":     "Save",
        "birthday":     "Birthday",
        "year":                 "Year",
        "month":    (
            "Month",
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December",
        ),
        "date":                 "{1} {2}th, {0}",
        "day":                  "Day",
        "warning":              "Warning",
        "close_without_saving": "All unsaved data will be lost. Do you want to close without saving?",
        "saved_successfully":   "Saved successfully",
        "saved_successfully_description":   "Your data has been saved successfully.",
        "permission_denied":    "Permission denied",
        "permission_denided_description":   "Your data file is currently being opened by another program.\nPlease try again later.",
        "unavailable_feature":  "Unavailable feature",
        "unavailable_feature_description":  "This feature is under development. Please try again later!",
        "crop":     "Crop image",
        "delete":           "Delete",
        "nickname":         "Nickname",
        "company":          "Company",
        "jobtitle":         "Job title",
        "custom":           "Custom",
        "home":             "Home",
        "work":             "Work",
        "school":           "School",
        "fax":              "Fax",
        "facebook":         "Facebook",
        "instagram":        "Instagram",
        "twitter":          "Twitter",
        "line":             "Line",
        "tiktok":           "Tiktok",
        "idcard":           "ID Card",
        "license":          "License",
        "passport":         "Passport",
        "vietcombank":      "VietcomBank",
        "sacombank":        "SacomBank",
        "techcombank":      "TechcomBank",
        "vietinbank":       "VietinBank",
        "bidv":             "BIDV",
        "agribank":         "AgriBank",
        "mbbank":           "MB Bank",
        "vpbank":           "VP Bank",
        "acb":              "ACB",
        "shb":              "SHB",
        "yucho":            "Yucho",
        "smbc":             "SMBC",
        "ufj":              "UFJ",
        "minato":           "Minato",
        "add_phone_number":     "Add phone number",
        "add_email":            "Add email",
        "add_sns_account":      "Add SNS account",
        "add_address":          "Add address",
        "add_birthday":         "Add birthday",
        "add_idcard":           "Add ID card",
        "add_bank":             "Add bank account",
        "idcard_number":        "ID card / license / passport number",
        "bank_account":         "Bank account",
        "bank_branch":          "Bank branch name",
        "custom_label":         "Custom label",
        "custom_label_question":    "What is your custom label?",
        "label_name":           "Label name",
        "note":                 "Note",
        "add note":             "Add note",
    },

    "vietnamese": {
        "contakuto":    "Contakuto",
        "search":       "Tìm kiếm",
        "edit":         "Sửa",
        "remove":       "Xóa",
        "signout":      "Đăng xuất",
        "cancel":       "Hủy bỏ",
        "ok":           "Đồng ý",
        "crop":         "Cắt ảnh",
        "profile_picture_description":      "Ảnh đại diện là ảnh thể hiện danh tính của chủ tài khoản.",
        "profile_picture":                  "Ảnh đại diện",
        "profile_picture_setting":          "Đổi ảnh đại diện.",
        "username": "Tên tài khoản",
        "fullname": "Tên đẩy đủ",
        "fullname_setting":         "Đổi tên đầy đủ.",
        "fullname_description":     "<p>- Tên đầy đủ sẽ được hiển thị ở góc trên bên phải của ứng dụng.</p>\n<p>- Tên đầy đủ chỉ được phép chứa chữ cái và chữ số.</p>",
        "password": "Mật khẩu",
        "password_setting":         "Đổi mật khẩu.",
        "password_description":     "<p>- Mật khẩu phải chứa tối thiểu 6 ký tự và tối đa 14 ký tự.</p><p>- Mật khẩu chỉ được phép chứa chữ cái và chữ số.</p>",
        "current_password":         "M.K hiện tại",
        "new_password":             "M.K mới",
        "confirm_password":         "Xác nhận M.K",
        "wrong_current_password":   "M.K hiện tại không đúng",
        "wrong_current_password_description":   "Bạn đã nhập sai mật khẩu hiện tại. Vui lòng thử lại.",
        "wrong_confirm_password":   "M.K xác nhận không đúng",
        "wrong_confirm_password_description":   "Bạn đã nhập sai mật khẩu xác nhận. Vui lòng thử lại",
        "pin_description":          "<p>- Mã PIN là một đoạn mã dùng để phục hồi mật khẩu.</p><p>- Mã PIN phải chứa 4 ký tự và tất cả phải là chữ số.</p>",
        "pin":                      "Mã PIN",
        "pin_setting":              "Đổi mã bảo mật.",
        "current_pin":              "PIN hiện tại",
        "new_pin":                  "PIN mới",
        "confirm_pin":              "Xác nhận PIN",
        "wrong_current_pin":        "Mã PIN hiện tại không đúng",
        "wrong_current_pin_description":    "Bạn đã nhập sai mã PIN hiện tại. Vui lòng thử lại.",
        "wrong_confirm_pin":        "Mã PIN xác nhận không đúng",
        "wrong_confirm_pin_description":    "Bạn đã xác nhận sai mã PIN. Vui lòng thử lại.",
        "language_description":     "<p>- Chức năng này cài đặt ngôn ngữ nào được thể hiện trên ứng dụng.</p><p>- Hiện tại chỉ có Tiếng Anh, Tiếng Việt và Tiếng Nhật được hỗ trợ.</p>",
        "language_setting":         "Đổi ngôn ngữ.",
        "choose_language":          "Chọn một ngôn ngữ:",
        "language":                 "Ngôn ngữ",
        "language_english":         "Tiếng Anh",
        "language_vietnamese":      "Tiếng Việt",
        "language_japanese":        "Tiếng Nhật",
        "theme_description":        "<p>- Chức năng này cài đặt giao diện của ứng dụng.</p><p>- Hiện tại chỉ có 2 giao diện được hỗ trợ là Sáng và Tối.</p>",
        "theme_setting":            "Đổi giao diện ứng dụng.",
        "theme":                    "Giao diện",
        "theme_light":              "Sáng",
        "theme_dark":               "Tối",
        "reboot_require":           "Yêu cầu khởi động lại",
        "reboot_require_description":   "Cài đặt này yêu cầu khởi động lại ứng dụng để có hiệu lực.\n Bạn có muốn khởi động lại không?",
        "save":     "Lưu",
        "birthday":     "Sinh nhật",
        "year":                 "Năm",
        "month":    (
            "Tháng",
            "Tháng 1",
            "Tháng 2",
            "Tháng 3",
            "Tháng 4",
            "Tháng 5",
            "Tháng 6",
            "Tháng 7",
            "Tháng 8",
            "Tháng 9",
            "Tháng 10",
            "Tháng 11",
            "Tháng 12",
        ),
        "date":                 "{2} {1}, {0}",
        "day":                  "Ngày",
        "warning":              "Cảnh báo",
        "close_without_saving": "Mọi dữ liệu chưa được lưu sẽ bị mất. Bạn có muốn thoát mà không lưu?",
        "saved_successfully":   "Lưu thành công",
        "saved_successfully_description":   "Dữ liệu của bạn đã được lưu thành công.",
        "permission_denied":    "Không thể lưu dữ liệu",
        "permission_denied_description":   "Tệp tin dữ liệu của bạn hiện đang được sử dụng bởi ứng dụng khác.\nVui lòng thử lại.",
        "unavailable_feature":  "Chức năng không khả dụng",
        "unavailable_feature_description":  "Chức năng này hiện đang được phát triển, vui lòng thử lại sau.",
        "crop":     "Cắt ảnh",
        "delete":           "Xóa",
        "nickname":         "Biệt danh",
        "company":          "Công ty",
        "jobtitle":         "Chức danh",
        "custom":           "Tùy chọn",
        "home":             "Nhà riêng",
        "work":             "Công ty",
        "school":           "Trường",
        "fax":              "Fax",
        "facebook":         "Facebook",
        "instagram":        "Instagram",
        "twitter":          "Twitter",
        "line":             "Line",
        "tiktok":           "Tiktok",
        "idcard":           "Căn cước",
        "license":          "BLX",
        "passport":         "Hộ chiếu",
        "vietcombank":      "VietcomBank",
        "sacombank":        "SacomBank",
        "techcombank":      "TechcomBank",
        "vietinbank":       "VietinBank",
        "bidv":             "BIDV",
        "agribank":         "AgriBank",
        "mbbank":           "MB Bank",
        "vpbank":           "VP Bank",
        "acb":              "ACB",
        "shb":              "SHB",
        "yucho":            "Yucho",
        "smbc":             "SMBC",
        "ufj":              "UFJ",
        "minato":           "Minato",
        "add_phone_number":     "Thêm số điện thoại",
        "add_email":            "Thêm email",
        "add_sns_account":      "Thêm mạng xã hội",
        "add_address":          "Thêm địa chỉ",
        "add_birthday":         "Thêm sinh nhật",
        "add_idcard":           "Thêm số căn cước",
        "add_bank":             "Thêm T.K ngân hàng",
        "idcard_number":        "Số căn cước / BLX / hộ chiếu",
        "bank_account":         "Số T.K ngân hàng",
        "bank_branch":          "Chi nhánh ngân hàng",
        "custom_label":         "Nhãn tùy chọn",
        "custom_label_question":    "Nhãn tùy chọn của bạn là gì?",
        "label_name":           "Tên nhãn",
        "note":                 "Ghi chú",
        "add_note":             "Thêm ghi chú",
    }
}